language: android
android:
  components:
    - build-tools-23.0.2

# fix gradle script execution
before_install:
 - chmod +x gradlew

# let's wait until they got it working
# before_script:
  # Create and start emulator
  # - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
  # - emulator -avd test -no-skin -no-audio -no-window &
  #- ./wait_for_emulator

# use base script coming from travis
# script:
#    - ./gradlew --stacktrace testDebug