language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

before_install:
  - chmod +x gradlew
  - echo 'DEBUG -- BEFORE UPDATE SDK'
  # Comment out the lines below to list suggested Android SDK components.
  - android list sdk -e || true
  # Comment out the lines below to list available Android SDK components.
  - android list sdk -a -e || true
  # Comment out the lines below to list available AVDs, Android targets and device definitions.
  - android list avd -c || true
  - android list target -c || true
  - android list device -c || true
