language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

before_install:
  - chmod +x gradlew
  - echo 'DEBUG -- BEFORE UPDATE SDK'
  # Comment out the lines below to list suggested Android SDK components.
  - android list sdk -e || true
  # Comment out the lines below to list available Android SDK components.
  - android list sdk -a -e || true
  # Comment out the lines below to list available AVDs, Android targets and device definitions.
  - android list avd -c || true
  - android list target -c || true
  - android list device -c || true
